#include "gfx/ags_shader_pipeline.h"
#include "gfx/ogl_headers.h"
#include <SDL.h>
#include <algorithm>
#include <cctype>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <fstream>
#include <sstream>

namespace AGS { namespace Engine { namespace OGL {
namespace {
struct V { float x,y,u,v; };
const V Q[4]={{-1,-1,0,0},{1,-1,1,0},{-1,1,0,1},{1,1,1,1}};
const char *VS="#version 120\nuniform mat4 MVPMatrix;attribute vec4 VertexCoord;attribute vec2 TexCoord;varying vec4 TEX0;void main(){gl_Position=MVPMatrix*VertexCoord;TEX0=vec4(TexCoord,0.0,1.0);}\n";
using G=void(*)(GLsizei,GLuint*); using D=void(*)(GLsizei,const GLuint*); using B=void(*)(GLenum,GLuint); using A=void(*)(GLenum,GLenum,GLenum,GLuint,GLint); using C=GLenum(*)(GLenum);
std::string T(std::string s){size_t a=s.find_first_not_of(" \t\r\n"),b=s.find_last_not_of(" \t\r\n");return a==std::string::npos?std::string():s.substr(a,b-a+1);} std::string L(std::string s){for(char &c:s)c=char(std::tolower((unsigned char)c));return s;} std::string U(std::string s){s=T(s);return s.size()>1&&s.front()=='"'&&s.back()=='"'?s.substr(1,s.size()-2):s;} std::string PD(const std::string&p){size_t n=p.find_last_of("/\\");return n==std::string::npos?".":p.substr(0,n);} std::string JP(const std::string&d,const std::string&p){return p.empty()||p[0]=='/'||(p.size()>1&&p[1]==':')?p:d+"/"+p;} bool S(const std::string&p,const char*e){size_t n=std::strlen(e);return p.size()>=n&&L(p.substr(p.size()-n))==L(e);} bool PB(const std::string&s,bool d){std::string v=L(U(s));return v=="true"||v=="1"?true:v=="false"||v=="0"?false:d;} int PI(const std::string&s,int d){char*e=nullptr;std::string v=U(s);long n=std::strtol(v.c_str(),&e,10);return e&&*e=='\0'?int(n):d;} float PF(const std::string&s,float d){char*e=nullptr;std::string v=U(s);float n=std::strtof(v.c_str(),&e);return e&&*e=='\0'?n:d;} int ST(const std::string&s){std::string v=L(U(s));return v=="viewport"?1:v=="absolute"?2:0;} int DIM(int t,float s,int src,int view){return std::max(1,int(std::lround(t==1?view*s:t==2?s:src*s)));}
std::string Stage(const std::string&s,const char*d){std::string p="#define "+std::string(d)+"\n";size_t n=s.find("#version");if(n!=std::string::npos){size_t e=s.find('\n',n);if(e!=std::string::npos)return s.substr(0,e+1)+p+s.substr(e+1);}return p+s;} bool Comb(const std::string&s){return s.find("defined(VERTEX)")!=std::string::npos||s.find("defined(FRAGMENT)")!=std::string::npos;}
}
AGSShaderPipeline::AGSShaderPipeline()=default; AGSShaderPipeline::~AGSShaderPipeline(){Clear();}
void AGSShaderPipeline::DestroyTarget(Target&t){if(t.fbo&&_delete_fbo)_delete_fbo(1,&t.fbo);if(t.texture)glDeleteTextures(1,&t.texture);t=Target();}
void AGSShaderPipeline::Clear(){for(auto&p:_passes)if(p.program)glDeleteProgram(p.program);_passes.clear();DestroyTarget(_targets[0]);DestroyTarget(_targets[1]);if(_capture_texture)glDeleteTextures(1,&_capture_texture);_capture_texture=0;}
bool AGSShaderPipeline::LoadShaderFile(const std::string&p,std::string&s,std::string&e)const{std::ifstream f(p.c_str(),std::ios::binary);if(!f){e="cannot read shader: "+p;return false;}std::ostringstream q;q<<f.rdbuf();s=q.str();if(s.empty()){e="empty shader: "+p;return false;}return true;}
bool AGSShaderPipeline::CompileShader(unsigned t,const std::string&s,unsigned&sh,std::string&e)const{sh=glCreateShader(t);if(!sh){e="glCreateShader failed";return false;}const char*p=s.c_str();glShaderSource(sh,1,&p,nullptr);glCompileShader(sh);GLint ok=0;glGetShaderiv(sh,GL_COMPILE_STATUS,&ok);if(ok)return true;GLint n=0;glGetShaderiv(sh,GL_INFO_LOG_LENGTH,&n);std::vector<char>log(std::max(1,n));if(n)glGetShaderInfoLog(sh,n,nullptr,log.data());e=log.data();glDeleteShader(sh);sh=0;return false;}
bool AGSShaderPipeline::CreateProgram(const std::string&v,const std::string&f,unsigned&p,std::string&e)const{unsigned a=0,b=0;if(!CompileShader(GL_VERTEX_SHADER,v,a,e))return false;if(!CompileShader(GL_FRAGMENT_SHADER,f,b,e)){glDeleteShader(a);return false;}p=glCreateProgram();if(!p){glDeleteShader(a);glDeleteShader(b);e="glCreateProgram failed";return false;}glAttachShader(p,a);glAttachShader(p,b);glBindAttribLocation(p,0,"VertexCoord");glBindAttribLocation(p,1,"TexCoord");glLinkProgram(p);glDeleteShader(a);glDeleteShader(b);GLint ok=0;glGetProgramiv(p,GL_LINK_STATUS,&ok);if(ok)return true;GLint n=0;glGetProgramiv(p,GL_INFO_LOG_LENGTH,&n);std::vector<char>log(std::max(1,n));if(n)glGetProgramInfoLog(p,n,nullptr,log.data());e=log.data();glDeleteProgram(p);p=0;return false;}
bool AGSShaderPipeline::AddPass(const std::string&p,const Pass*preset,std::string&e){std::string s;if(!LoadShaderFile(p,s,e))return false;Pass x;if(preset)x=*preset;x.source_path=p;std::string v=Comb(s)?Stage(s,"VERTEX"):VS,f=Comb(s)?Stage(s,"FRAGMENT"):s;if(!CreateProgram(v,f,x.program,e))return false;x.texture=glGetUniformLocation(x.program,"Texture");if(x.texture<0)x.texture=glGetUniformLocation(x.program,"uTexture");x.texture_size=glGetUniformLocation(x.program,"TextureSize");x.input_size=glGetUniformLocation(x.program,"SourceSize");if(x.input_size<0)x.input_size=glGetUniformLocation(x.program,"InputSize");x.output_size=glGetUniformLocation(x.program,"OutputSize");x.original_size=glGetUniformLocation(x.program,"OriginalSize");x.frame_count=glGetUniformLocation(x.program,"FrameCount");x.frame_direction=glGetUniformLocation(x.program,"FrameDirection");_passes.push_back(x);return true;}
bool AGSShaderPipeline::ParseChain(const std::string&p,std::vector<std::string>&o,std::string&e)const{std::string s;if(!LoadShaderFile(p,s,e))return false;std::istringstream in(s);std::string l;while(std::getline(in,l)){l=T(l);if(l.compare(0,5,"pass=")==0)o.push_back(JP(PD(p),U(l.substr(5))));}if(o.empty())e="shader chain has no passes: "+p;return !o.empty();}
bool AGSShaderPipeline::ParsePreset(const std::string&p,std::vector<Pass>&o,std::string&e)const{std::string s;if(!LoadShaderFile(p,s,e))return false;struct E{std::string p;Pass v;};std::vector<E>a;int n=-1;std::istringstream in(s);std::string l;while(std::getline(in,l)){l=T(l);if(l.empty()||l[0]=='#')continue;size_t q=l.find('=');if(q==std::string::npos)continue;std::string k=T(l.substr(0,q)),v=U(l.substr(q+1));if(k=="shaders"){n=PI(v,-1);continue;}if(k.rfind("shader",0)==0&&k.size()>6&&std::isdigit((unsigned char)k[6])){int i=PI(k.substr(6),-1);if(i>=0){if((size_t)i>=a.size())a.resize(i+1);a[i].p=JP(PD(p),v);}continue;}size_t d=k.size();while(d&&std::isdigit((unsigned char)k[d-1]))--d;if(d==k.size())continue;int i=PI(k.substr(d),-1);if(i<0)continue;if((size_t)i>=a.size())a.resize(i+1);std::string b=k.substr(0,d);if(b=="filter_linear")a[i].v.filter_linear=PB(v,false);else if(b=="scale")a[i].v.scale_x=a[i].v.scale_y=PF(v,1);else if(b=="scale_x")a[i].v.scale_x=PF(v,1);else if(b=="scale_y")a[i].v.scale_y=PF(v,1);else if(b=="scale_type")a[i].v.scale_type=ST(v);}if(n<0)n=int(a.size());if(n<=0){e="glslp has no shaders: "+p;return false;}o.clear();for(int i=0;i<n;i++){if(i>=int(a.size())||a[i].p.empty()){e="missing shader"+std::to_string(i);return false;}a[i].v.source_path=a[i].p;o.push_back(a[i].v);}return true;}
bool AGSShaderPipeline::Load(const std::string&p,std::string&e){Clear();if(S(p,".glslp")){std::vector<Pass>a;if(!ParsePreset(p,a,e))return false;for(auto&x:a)if(!AddPass(x.source_path,&x,e)){Clear();return false;}}else if(S(p,".agschain")){std::vector<std::string>a;if(!ParseChain(p,a,e))return false;for(auto&x:a)if(!AddPass(x,nullptr,e)){Clear();return false;}}else if(!AddPass(p,nullptr,e)){Clear();return false;}return true;}
bool AGSShaderPipeline::LoadFboFunctions(std::string&e){if(_gen_fbo&&_delete_fbo&&_bind_fbo&&_attach_texture&&_check_fbo)return true;_gen_fbo=(G)SDL_GL_GetProcAddress("glGenFramebuffersEXT");_delete_fbo=(D)SDL_GL_GetProcAddress("glDeleteFramebuffersEXT");_bind_fbo=(B)SDL_GL_GetProcAddress("glBindFramebufferEXT");_attach_texture=(A)SDL_GL_GetProcAddress("glFramebufferTexture2DEXT");_check_fbo=(C)SDL_GL_GetProcAddress("glCheckFramebufferStatusEXT");if(!_gen_fbo||!_delete_fbo||!_bind_fbo||!_attach_texture||!_check_fbo){e="EXT_framebuffer_object unavailable";return false;}return true;}
bool AGSShaderPipeline::EnsureCaptureTexture(int w,int h,std::string&e){if(_capture_texture&&_capture_width==w&&_capture_height==h)return true;glDeleteTextures(1,&_capture_texture);glGenTextures(1,&_capture_texture);if(!_capture_texture){e="capture texture failed";return false;}glBindTexture(GL_TEXTURE_2D,_capture_texture);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,nullptr);glBindTexture(GL_TEXTURE_2D,0);_capture_width=w;_capture_height=h;return true;}
bool AGSShaderPipeline::EnsureTarget(Target&t,int w,int h,bool linear,std::string&e){if(!LoadFboFunctions(e))return false;if(t.fbo&&t.width==w&&t.height==h)return true;DestroyTarget(t);t.width=w;t.height=h;glGenTextures(1,&t.texture);glBindTexture(GL_TEXTURE_2D,t.texture);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,linear?GL_LINEAR:GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,linear?GL_LINEAR:GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_CLAMP_TO_EDGE);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_CLAMP_TO_EDGE);glTexImage2D(GL_TEXTURE_2D,0,GL_RGBA,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,nullptr);_gen_fbo(1,&t.fbo);_bind_fbo(GL_FRAMEBUFFER_EXT,t.fbo);_attach_texture(GL_FRAMEBUFFER_EXT,GL_COLOR_ATTACHMENT0_EXT,GL_TEXTURE_2D,t.texture,0);if(_check_fbo(GL_FRAMEBUFFER_EXT)!=GL_FRAMEBUFFER_COMPLETE_EXT){e="incomplete shader framebuffer";DestroyTarget(t);_bind_fbo(GL_FRAMEBUFFER_EXT,0);return false;}return true;}
void AGSShaderPipeline::Apply(int iw,int ih,int ow,int oh){if(_passes.empty()||iw<=0||ih<=0||ow<=0||oh<=0)return;std::string e;if(!EnsureCaptureTexture(ow,oh,e))return;GLint oldfb=0,oldp=0,olda=0,oldaTex=GL_TEXTURE0,oldt=0,oldv[4];glGetIntegerv(GL_FRAMEBUFFER_BINDING,&oldfb);glGetIntegerv(GL_CURRENT_PROGRAM,&oldp);glGetIntegerv(GL_ARRAY_BUFFER_BINDING,&olda);glGetIntegerv(GL_ACTIVE_TEXTURE,&oldaTex);glGetIntegerv(GL_TEXTURE_BINDING_2D,&oldt);glGetIntegerv(GL_VIEWPORT,oldv);GLboolean blend=glIsEnabled(GL_BLEND),depth=glIsEnabled(GL_DEPTH_TEST),sc=glIsEnabled(GL_SCISSOR_TEST);glDisable(GL_BLEND);glDisable(GL_DEPTH_TEST);glDisable(GL_SCISSOR_TEST);glBindBuffer(GL_ARRAY_BUFFER,0);glBindTexture(GL_TEXTURE_2D,_capture_texture);glReadBuffer(GL_BACK);glCopyTexSubImage2D(GL_TEXTURE_2D,0,0,0,0,0,ow,oh);unsigned tex=_capture_texture;int sw=ow,sh=oh;for(size_t i=0;i<_passes.size();++i){const Pass&p=_passes[i];bool last=i+1==_passes.size();int w=last?ow:DIM(p.scale_type,p.scale_x,sw,ow),h=last?oh:DIM(p.scale_type,p.scale_y,sh,oh);if(!last){if(!EnsureTarget(_targets[i&1],w,h,p.filter_linear,e))break;_bind_fbo(GL_FRAMEBUFFER_EXT,_targets[i&1].fbo);}else{if(_bind_fbo)_bind_fbo(GL_FRAMEBUFFER_EXT,(unsigned)oldfb);else glBindFramebufferEXT(GL_FRAMEBUFFER_EXT,(unsigned)oldfb);}glViewport(0,0,w,h);glUseProgram(p.program);glActiveTexture(GL_TEXTURE0);glBindTexture(GL_TEXTURE_2D,tex);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,p.filter_linear?GL_LINEAR:GL_NEAREST);glTexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,p.filter_linear?GL_LINEAR:GL_NEAREST);if(p.texture>=0)glUniform1i(p.texture,0);if(p.texture_size>=0)glUniform2f(p.texture_size,float(sw),float(sh));if(p.input_size>=0)glUniform2f(p.input_size,float(sw),float(sh));if(p.output_size>=0)glUniform2f(p.output_size,float(w),float(h));if(p.original_size>=0)glUniform2f(p.original_size,float(iw),float(ih));if(p.frame_count>=0)glUniform1i(p.frame_count,(GLint)_frame_count);if(p.frame_direction>=0)glUniform1i(p.frame_direction,1);GLint m=glGetUniformLocation(p.program,"MVPMatrix");if(m>=0){const GLfloat I[16]={1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1};glUniformMatrix4fv(m,1,GL_FALSE,I);}glEnableVertexAttribArray(0);glEnableVertexAttribArray(1);glVertexAttribPointer(0,2,GL_FLOAT,GL_FALSE,sizeof(V),&Q[0].x);glVertexAttribPointer(1,2,GL_FLOAT,GL_FALSE,sizeof(V),&Q[0].u);glDrawArrays(GL_TRIANGLE_STRIP,0,4);glDisableVertexAttribArray(0);glDisableVertexAttribArray(1);if(!last){tex=_targets[i&1].texture;sw=w;sh=h;}}
if(_bind_fbo)_bind_fbo(GL_FRAMEBUFFER_EXT,(unsigned)oldfb);else glBindFramebufferEXT(GL_FRAMEBUFFER_EXT,(unsigned)oldfb);glUseProgram(oldp);glBindBuffer(GL_ARRAY_BUFFER,olda);glActiveTexture(oldaTex);glBindTexture(GL_TEXTURE_2D,oldt);glViewport(oldv[0],oldv[1],oldv[2],oldv[3]);if(blend)glEnable(GL_BLEND);else glDisable(GL_BLEND);if(depth)glEnable(GL_DEPTH_TEST);else glDisable(GL_DEPTH_TEST);if(sc)glEnable(GL_SCISSOR_TEST);else glDisable(GL_SCISSOR_TEST);++_frame_count;}
}}}