#pragma once

/*
 * Standalone AGS native-frame discovery for the LD_PRELOAD injector.
 *
 * This mirrors the host-side architecture used by ScummVM's OpenGL
 * LibRetroPipeline: feed the shader chain the game's logical render target,
 * not an already-scaled presentation backbuffer. No ScummVM code or runtime is
 * required; the source is discovered from AGS' own OpenGL FBO activity.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

struct AgsNativeSource {
    unsigned texture = 0;
    unsigned fbo = 0;
    int width = 0;
    int height = 0;
    int texture_width = 0;
    int texture_height = 0;
};

// Returns the last AGS offscreen color target that was presented to the screen
// during the current frame. This is opt-in via AGS_SHADER_NATIVE_SOURCE=auto/1.
bool ags_native_source_acquire(int output_width,
                               int output_height,
                               AgsNativeSource &source);

// Ignore FBO traffic generated by the shader injector itself.
void ags_native_source_set_pipeline_active(bool active);
